SA-PVINT for Elliptic Boundary Value Problems: LaplaceProblem< dim, degree > Class Template Reference
LaplaceProblem< dim, degree > Class Template Reference
#include <laplace_problem.h>
Public Types
using VectorType = LA::MPI::Vector
using PreconditionAMG = LA::MPI::PreconditionAMG
using PreconditionJacobi = LA::MPI::PreconditionJacobi
using MatrixFreeLevelVector = LinearAlgebra::distributed::Vector< float >
using MatrixFreeActiveVector = LinearAlgebra::distributed::Vector< double >
using MatrixFreeLevelMatrix = MatrixFreeOperators::LaplaceOperator< dim, degree, degree+1, 1, MatrixFreeLevelVector >
using MatrixFreeActiveMatrix = MatrixFreeOperators::LaplaceOperator< dim, degree, degree+1, 1, MatrixFreeActiveVector >
using MatrixFreeLevelMassMatrix = MatrixFreeOperators::MassOperator< dim, degree, degree+1, 1, MatrixFreeLevelVector >
using MatrixFreeActiveMassMatrix = MatrixFreeOperators::MassOperator< dim, degree, degree+1, 1, MatrixFreeActiveVector >
Public Member Functions
LaplaceProblem (const LaplaceProblemSettings< dim > &settings)
void run ()
void make_grid ()
void setup_system (const unsigned int cycle)
void setup_multigrid ()
void assemble_multigrid ()
void assemble_rhs ()
void solve (const unsigned int cycle)
void estimate ()
void estimate (const unsigned int eigenvector_index)
void refine_grid ()
void output_results (const unsigned int cycle)
void print_grid_info () const
Public Attributes
const LaplaceProblemSettings< dim > & settings
MPI_Comm mpi_communicator
ConditionalOStream pcout
parallel::distributed::Triangulation< dim > triangulation
const MappingQ1< dim > mapping
FE_Q< dim > fe
DoFHandler< dim > dof_handler
parallel::distributed::SolutionTransfer< dim, VectorType > solution_transfer
parallel::distributed::SolutionTransfer< dim, MatrixFreeActiveVector > eigenvectors_transfer
IndexSet locally_owned_dofs
IndexSet locally_relevant_dofs
AffineConstraints< double > constraints
MatrixFreeActiveMatrix stiffness_operator
MatrixFreeActiveMassMatrix mass_operator
VectorType solution
VectorType locally_relevant_solution
VectorType right_hand_side
std::vector< MatrixFreeActiveVector > eigenvectors
std::vector< double > eigenvalues
Vector< double > estimated_error_square_per_cell
MGLevelObject< MatrixFreeLevelMatrix > mg_stiffness_operator
MGLevelObject< MatrixFreeLevelMassMatrix > mg_mass_operator
MGConstrainedDoFs mg_constrained_dofs
MGConstrainedDoFs mg_constrained_mass_dofs
TimerOutput computing_timer
Friends
template<int , int >
class TestBench
Detailed Description
template<int dim, int degree>
class LaplaceProblem< dim, degree >
Definition at line 55 of file laplace_problem.h.
Member Typedef Documentation
MatrixFreeActiveMassMatrix
template<int dim, int degree> using LaplaceProblem< dim, degree >::MatrixFreeActiveMassMatrix = MatrixFreeOperators:: MassOperator<dim, degree, degree + 1, 1, MatrixFreeActiveVector>
Definition at line 78 of file laplace_problem.h.
MatrixFreeActiveMatrix
template<int dim, int degree> using LaplaceProblem< dim, degree >::MatrixFreeActiveMatrix = MatrixFreeOperators:: LaplaceOperator<dim, degree, degree + 1, 1, MatrixFreeActiveVector>
Definition at line 72 of file laplace_problem.h.
MatrixFreeActiveVector
template<int dim, int degree> using LaplaceProblem< dim, degree >::MatrixFreeActiveVector = LinearAlgebra::distributed::Vector<double>
Definition at line 67 of file laplace_problem.h.
MatrixFreeLevelMassMatrix
template<int dim, int degree> using LaplaceProblem< dim, degree >::MatrixFreeLevelMassMatrix = MatrixFreeOperators:: MassOperator<dim, degree, degree + 1, 1, MatrixFreeLevelVector>
Definition at line 75 of file laplace_problem.h.
MatrixFreeLevelMatrix
template<int dim, int degree> using LaplaceProblem< dim, degree >::MatrixFreeLevelMatrix = MatrixFreeOperators:: LaplaceOperator<dim, degree, degree + 1, 1, MatrixFreeLevelVector>
Definition at line 69 of file laplace_problem.h.
MatrixFreeLevelVector
template<int dim, int degree> using LaplaceProblem< dim, degree >::MatrixFreeLevelVector = LinearAlgebra::distributed::Vector<float>
Definition at line 66 of file laplace_problem.h.
PreconditionAMG
template<int dim, int degree> using LaplaceProblem< dim, degree >::PreconditionAMG = LA::MPI::PreconditionAMG
Definition at line 63 of file laplace_problem.h.
PreconditionJacobi
template<int dim, int degree> using LaplaceProblem< dim, degree >::PreconditionJacobi = LA::MPI::PreconditionJacobi
Definition at line 64 of file laplace_problem.h.
VectorType
template<int dim, int degree> using LaplaceProblem< dim, degree >::VectorType = LA::MPI::Vector
Definition at line 62 of file laplace_problem.h.
Constructor & Destructor Documentation
LaplaceProblem()
template<int dim, int degree> LaplaceProblem< dim, degree >::LaplaceProblem (const LaplaceProblemSettings< dim > & settings)
Definition at line 58 of file laplace_problem.cc.
References construct_multigrid_hierarchy, this_mpi_process(), and triangulation.
Member Function Documentation
assemble_multigrid()
template<int dim, int degree> void LaplaceProblem< dim, degree >::assemble_multigrid ()
assemble_rhs()
template<int dim, int degree> void LaplaceProblem< dim, degree >::assemble_rhs
Definition at line 313 of file laplace_problem.cc.
References VectorOperation::add, LinearAlgebra::distributed::Vector< Number, MemorySpace >::compress(), ChangeVectorTypes::copy(), FEEvaluation< dim, fe_degree, n_q_points_1d, n_components_, Number, VectorizedArrayType >::evaluate(), evaluate_function(), FEEvaluation< dim, fe_degree, n_q_points_1d, n_components_, Number, VectorizedArrayType >::get_gradient(), EvaluationFlags::gradients, FEEvaluation< dim, fe_degree, n_q_points_1d, n_components_, Number, VectorizedArrayType >::integrate_scatter(), FEEvaluation< dim, fe_degree, n_q_points_1d, n_components_, Number, VectorizedArrayType >::n_q_points, FEEvaluation< dim, fe_degree, n_q_points_1d, n_components_, Number, VectorizedArrayType >::quadrature_point(), FEEvaluation< dim, fe_degree, n_q_points_1d, n_components_, Number, VectorizedArrayType >::read_dof_values_plain(), FEEvaluation< dim, fe_degree, n_q_points_1d, n_components_, Number, VectorizedArrayType >::reinit(), FEEvaluation< dim, fe_degree, n_q_points_1d, n_components_, Number, VectorizedArrayType >::submit_gradient(), FEEvaluation< dim, fe_degree, n_q_points_1d, n_components_, Number, VectorizedArrayType >::submit_value(), LinearAlgebra::distributed::Vector< Number, MemorySpace >::update_ghost_values(), and EvaluationFlags::values.
estimate() [1/2]
template<int dim, int degree> void LaplaceProblem< dim, degree >::estimate
Compute a Residual based error estimator on the source problem
Definition at line 566 of file laplace_problem.cc.
References MeshWorker::assemble_ghost_faces_both, MeshWorker::assemble_own_cells, MeshWorker::assemble_own_interior_faces_once, CopyData::FaceData::cell_indices, FEInterfaceValues< dim, spacedim >::get_fe_face_values(), FEValues< dim >::get_function_hessians(), hessians, numbers::invalid_unsigned_int, FEInterfaceValues< dim, spacedim >::JxW(), FEValues< dim >::JxW(), MeshWorker::mesh_loop(), FEInterfaceValues< dim, spacedim >::n_quadrature_points, FEValues< dim >::n_quadrature_points, FEInterfaceValues< dim, spacedim >::normal(), FEInterfaceValues< dim, spacedim >::reinit(), FEValues< dim >::reinit(), Utilities::MPI::sum(), trace(), triangulation, update_gradients, update_hessians, update_JxW_values, update_normal_vectors, update_quadrature_points, update_values, and CopyData::FaceData::values.
estimate() [2/2]
template<int dim, int degree> void LaplaceProblem< dim, degree >::estimate (const unsigned int eigenvector_index)
Compute a Residual based error estimator on the eigenvalue problem. The argument is used only to accumulate the estimator based on each computed eigenvector and eigenvalue pair.
Definition at line 700 of file laplace_problem.cc.
References MeshWorker::assemble_ghost_faces_both, MeshWorker::assemble_own_cells, MeshWorker::assemble_own_interior_faces_once, CopyData::FaceData::cell_indices, ChangeVectorTypes::copy(), eigenvectors(), FEInterfaceValues< dim, spacedim >::get_fe_face_values(), FEValues< dim >::get_function_hessians(), hessians, numbers::invalid_unsigned_int, FEValues< dim >::JxW(), FEInterfaceValues< dim, spacedim >::JxW(), MeshWorker::mesh_loop(), FEInterfaceValues< dim, spacedim >::n_quadrature_points, FEValues< dim >::n_quadrature_points, FEInterfaceValues< dim, spacedim >::normal(), FEInterfaceValues< dim, spacedim >::reinit(), FEValues< dim >::reinit(), Utilities::MPI::sum(), trace(), triangulation, update_gradients, update_hessians, update_JxW_values, update_normal_vectors, update_quadrature_points, update_values, and CopyData::FaceData::values.
make_grid()
template<int dim, int degree> void LaplaceProblem< dim, degree >::make_grid
Create the grid from the specification in the settings.
Definition at line 79 of file laplace_problem.cc.
References GridGenerator::generate_from_name_and_arguments(), read_grid_and_cad_files(), triangulation, and GridOut::write_vtk().
output_results()
template<int dim, int degree> void LaplaceProblem< dim, degree >::output_results (const unsigned int cycle)
Definition at line 878 of file laplace_problem.cc.
References DataOut< dim >::add_data_vector(), DataOut< dim >::attach_dof_handler(), DataOut< dim >::build_patches(), eigenvectors(), Utilities::int_to_string(), level, DataOut< dim >::set_flags(), Vector< float >::size(), Utilities::MPI::this_mpi_process(), triangulation, DataOutBase::VtkFlags::write_higher_order_cells, GridOut::write_mesh_per_processor_as_vtu(), DataOutBase::write_pvd_record(), and DataOut< dim >::write_vtu_with_pvtu_record().
print_grid_info()
template<int dim, int degree> void LaplaceProblem< dim, degree >::print_grid_info
Definition at line 968 of file laplace_problem.cc.
References triangulation, and MGTools::workload_imbalance().
refine_grid()
template<int dim, int degree> void LaplaceProblem< dim, degree >::refine_grid
Definition at line 839 of file laplace_problem.cc.
References Assert, eigenvectors(), ExcInternalError(), parallel::distributed::GridRefinement::refine_and_coarsen_fixed_fraction(), parallel::distributed::GridRefinement::refine_and_coarsen_fixed_number(), and triangulation.
run()
template<int dim, int degree> void LaplaceProblem< dim, degree >::run
Definition at line 988 of file laplace_problem.cc.
Referenced by main().
setup_multigrid()
template<int dim, int degree> void LaplaceProblem< dim, degree >::setup_multigrid
Definition at line 212 of file laplace_problem.cc.
References AffineConstraints< number >::add_lines(), AffineConstraints< number >::close(), DoFTools::extract_locally_relevant_level_dofs(), level, make_coefficient_table(), MatrixFree< dim, Number, VectorizedArrayType >::mg_level, AffineConstraints< number >::reinit(), triangulation, update_gradients, update_JxW_values, update_quadrature_points, and update_values.
setup_system()
template<int dim, int degree> void LaplaceProblem< dim, degree >::setup_system (const unsigned int cycle)
Definition at line 107 of file laplace_problem.cc.
References AffineConstraints< double >::close(), eigenvalues, eigenvectors(), DoFTools::extract_locally_relevant_dofs(), Utilities::generate_normal_random_number(), VectorTools::interpolate_boundary_values(), locally_owned_dofs(), make_coefficient_table(), DoFTools::make_hanging_node_constraints(), MatrixFree< dim, Number, VectorizedArrayType >::reinit(), update_gradients, update_JxW_values, update_quadrature_points, and update_values.
solve()
template<int dim, int degree> void LaplaceProblem< dim, degree >::solve (const unsigned int cycle)
Definition at line 363 of file laplace_problem.cc.
References MGTransferMatrixFree< dim, Number >::build(), ChangeVectorTypes::copy(), e(), eigenvalues, eigenvectors(), SolverControl::enable_history_data(), MGSmootherPrecondition< MatrixType, PreconditionerType, VectorType >::initialize(), SolverControl::last_step(), level, one_step_pinvit(), MGLevelObject< Object >::resize(), MGSmootherPrecondition< MatrixType, PreconditionerType, VectorType >::set_steps(), solver, Patterns::Tools::to_string(), triangulation, LinearAlgebra::distributed::Vector< Number, MemorySpace >::update_ghost_values(), and PreconditionMG< dim, VectorType, TRANSFER >::vmult().
Friends And Related Function Documentation
TestBench
template<int dim, int degree> template<int , int > friend class TestBench friend
Make sure google tests can access private members.
Definition at line 156 of file laplace_problem.h.
Member Data Documentation
computing_timer
template<int dim, int degree> TimerOutput LaplaceProblem< dim, degree >::computing_timer
Definition at line 150 of file laplace_problem.h.
constraints
template<int dim, int degree> AffineConstraints<double> LaplaceProblem< dim, degree >::constraints
Definition at line 134 of file laplace_problem.h.
dof_handler
template<int dim, int degree> DoFHandler<dim> LaplaceProblem< dim, degree >::dof_handler
Definition at line 127 of file laplace_problem.h.
eigenvalues
template<int dim, int degree> std::vector<double> LaplaceProblem< dim, degree >::eigenvalues
Definition at line 142 of file laplace_problem.h.
eigenvectors
template<int dim, int degree> std::vector<MatrixFreeActiveVector> LaplaceProblem< dim, degree >::eigenvectors
Definition at line 141 of file laplace_problem.h.
eigenvectors_transfer
template<int dim, int degree> parallel::distributed::SolutionTransfer<dim, MatrixFreeActiveVector> LaplaceProblem< dim, degree >::eigenvectors_transfer
Definition at line 130 of file laplace_problem.h.
estimated_error_square_per_cell
template<int dim, int degree> Vector<double> LaplaceProblem< dim, degree >::estimated_error_square_per_cell
Definition at line 143 of file laplace_problem.h.
fe
template<int dim, int degree> FE_Q<dim> LaplaceProblem< dim, degree >::fe
Definition at line 125 of file laplace_problem.h.
locally_owned_dofs
template<int dim, int degree> IndexSet LaplaceProblem< dim, degree >::locally_owned_dofs
Definition at line 132 of file laplace_problem.h.
locally_relevant_dofs
template<int dim, int degree> IndexSet LaplaceProblem< dim, degree >::locally_relevant_dofs
Definition at line 133 of file laplace_problem.h.
locally_relevant_solution
template<int dim, int degree> VectorType LaplaceProblem< dim, degree >::locally_relevant_solution
Definition at line 139 of file laplace_problem.h.
mapping
template<int dim, int degree> const MappingQ1<dim> LaplaceProblem< dim, degree >::mapping
Definition at line 124 of file laplace_problem.h.
mass_operator
template<int dim, int degree> MatrixFreeActiveMassMatrix LaplaceProblem< dim, degree >::mass_operator
Definition at line 137 of file laplace_problem.h.
mg_constrained_dofs
template<int dim, int degree> MGConstrainedDoFs LaplaceProblem< dim, degree >::mg_constrained_dofs
Definition at line 147 of file laplace_problem.h.
mg_constrained_mass_dofs
template<int dim, int degree> MGConstrainedDoFs LaplaceProblem< dim, degree >::mg_constrained_mass_dofs
Definition at line 148 of file laplace_problem.h.
mg_mass_operator
template<int dim, int degree> MGLevelObject<MatrixFreeLevelMassMatrix> LaplaceProblem< dim, degree >::mg_mass_operator
Definition at line 146 of file laplace_problem.h.
mg_stiffness_operator
template<int dim, int degree> MGLevelObject<MatrixFreeLevelMatrix> LaplaceProblem< dim, degree >::mg_stiffness_operator
Definition at line 145 of file laplace_problem.h.
mpi_communicator
template<int dim, int degree> MPI_Comm LaplaceProblem< dim, degree >::mpi_communicator
Definition at line 120 of file laplace_problem.h.
pcout
template<int dim, int degree> ConditionalOStream LaplaceProblem< dim, degree >::pcout
Definition at line 121 of file laplace_problem.h.
right_hand_side
template<int dim, int degree> VectorType LaplaceProblem< dim, degree >::right_hand_side
Definition at line 140 of file laplace_problem.h.
settings
template<int dim, int degree> const LaplaceProblemSettings<dim>& LaplaceProblem< dim, degree >::settings
Definition at line 118 of file laplace_problem.h.
solution
template<int dim, int degree> VectorType LaplaceProblem< dim, degree >::solution
Definition at line 138 of file laplace_problem.h.
solution_transfer
template<int dim, int degree> parallel::distributed::SolutionTransfer<dim, VectorType> LaplaceProblem< dim, degree >::solution_transfer
Definition at line 128 of file laplace_problem.h.
stiffness_operator
template<int dim, int degree> MatrixFreeActiveMatrix LaplaceProblem< dim, degree >::stiffness_operator
Definition at line 136 of file laplace_problem.h.
triangulation
template<int dim, int degree> parallel::distributed::Triangulation<dim> LaplaceProblem< dim, degree >::triangulation
Definition at line 123 of file laplace_problem.h.
The documentation for this class was generated from the following files:
/github/workspace/include/laplace_problem.h
/github/workspace/source/laplace_problem.cc