S-AFEM and SA-PINVIT for Elliptic Boundary Value Problems: InnerControl Class Reference
InnerControl Class Reference
#include <inner_control.h>
Public Member Functions
InnerControl ()=default
InnerControl (const unsigned int max_iterations, const double tolerance, const double reduction, bool log, bool loglast)
virtual SolverControl::State check (const unsigned int iteration, const double check_value) override
Public Member Functions inherited from ReductionControl
ReductionControl (const unsigned int maxiter=100, const double tolerance=1.e-10, const double reduce=1.e-2, const bool log_history=false, const bool log_result=true)
ReductionControl (const SolverControl &c)
ReductionControl & operator= (const SolverControl &c)
virtual ~ReductionControl () override=default
void parse_parameters (ParameterHandler &param)
double reduction () const
double set_reduction (const double)
State last_check () const
double initial_value () const
double last_value () const
unsigned int last_step () const
unsigned int max_steps () const
unsigned int set_max_steps (const unsigned int)
void set_failure_criterion (const double rel_failure_residual)
void clear_failure_criterion ()
double tolerance () const
double set_tolerance (const double)
void enable_history_data ()
const std::vector< double > & get_history_data () const
double average_reduction () const
double final_reduction () const
double step_reduction (unsigned int step) const
void log_history (const bool)
bool log_history () const
unsigned int log_frequency (unsigned int)
void log_result (const bool)
bool log_result () const
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from SolverControl
SolverControl (const unsigned int n=100, const double tol=1.e-10, const bool log_history=false, const bool log_result=true)
virtual ~SolverControl () override=default
void parse_parameters (ParameterHandler &param)
State last_check () const
double initial_value () const
double last_value () const
unsigned int last_step () const
unsigned int max_steps () const
unsigned int set_max_steps (const unsigned int)
void set_failure_criterion (const double rel_failure_residual)
void clear_failure_criterion ()
double tolerance () const
double set_tolerance (const double)
void enable_history_data ()
const std::vector< double > & get_history_data () const
double average_reduction () const
double final_reduction () const
double step_reduction (unsigned int step) const
void log_history (const bool)
bool log_history () const
unsigned int log_frequency (unsigned int)
void log_result (const bool)
bool log_result () const
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from Subscriptor
Subscriptor ()
Subscriptor (const Subscriptor &)
Subscriptor (Subscriptor &&) noexcept
virtual ~Subscriptor ()
Subscriptor & operator= (const Subscriptor &)
Subscriptor & operator= (Subscriptor &&) noexcept
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Additional Inherited Members
Public Types inherited from ReductionControl
enum State
Public Types inherited from SolverControl
enum State
Static Public Member Functions inherited from ReductionControl
static void declare_parameters (ParameterHandler &param)
static ::ExceptionBase & ExcHistoryDataRequired ()
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from SolverControl
static void declare_parameters (ParameterHandler &param)
static ::ExceptionBase & ExcHistoryDataRequired ()
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from Subscriptor
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Public Attributes inherited from ReductionControl
iterate
success
failure
Public Attributes inherited from SolverControl
iterate
success
failure
Protected Attributes inherited from ReductionControl
double reduce
double reduced_tol
unsigned int maxsteps
double tol
State lcheck
double initial_val
double lvalue
unsigned int lstep
bool check_failure
double relative_failure_residual
double failure_residual
bool m_log_history
unsigned int m_log_frequency
bool m_log_result
bool history_data_enabled
std::vector< double > history_data
Protected Attributes inherited from SolverControl
unsigned int maxsteps
double tol
State lcheck
double initial_val
double lvalue
unsigned int lstep
bool check_failure
double relative_failure_residual
double failure_residual
bool m_log_history
unsigned int m_log_frequency
bool m_log_result
bool history_data_enabled
std::vector< double > history_data
Detailed Description
Definition at line 9 of file inner_control.h.
Constructor & Destructor Documentation
InnerControl() [1/2]
InnerControl::InnerControl () default
InnerControl() [2/2]
InnerControl::InnerControl (const unsigned int max_iterations, const double tolerance, const double reduction, bool log, bool loglast)
Definition at line 3 of file inner_control.cc.
References log().
Member Function Documentation
check()
SolverControl::State InnerControl::check (const unsigned int iteration, const double check_value) override virtual
Reimplemented from ReductionControl.
Definition at line 14 of file inner_control.cc.
References ReductionControl::check(), ReductionControl::max_steps(), and SolverControl::success.
The documentation for this class was generated from the following files:
/github/workspace/include/inner_control.h
/github/workspace/source/inner_control.cc