Template Deal.II Application: ChangeVectorTypes Namespace Reference
ChangeVectorTypes Namespace Reference
Functions
template<typename number >
void copy (LA::MPI::Vector &out, const dealii::LinearAlgebra::distributed::Vector< number > &in)
template<typename number >
void copy (dealii::LinearAlgebra::distributed::Vector< number > &out, const LA::MPI::Vector &in)
Function Documentation
copy() [1/2]
template<typename number > void ChangeVectorTypes::copy (dealii::LinearAlgebra::distributed::Vector< number > & out, const LA::MPI::Vector & in)
Definition at line 97 of file utilities.h.
References AssertThrow, ExcMessage(), and VectorOperation::insert.
copy() [2/2]
template<typename number > void ChangeVectorTypes::copy (LA::MPI::Vector & out, const dealii::LinearAlgebra::distributed::Vector< number > & in)
Definition at line 78 of file utilities.h.
References AssertThrow, ExcMessage(), and VectorOperation::insert.
Referenced by LaplaceProblem< dim, degree >::assemble_rhs(), and LaplaceProblem< dim, degree >::solve().