S-AFEM and SA-PINVIT for Elliptic Boundary Value Problems: /github/workspace/include/pinvit.h File Reference
pinvit.h File Reference
#include <deal.II/base/exceptions.h>
Functions
template<class VectorType , class StiffnessMatrixType , class MassMatrixType >
VectorType::value_type compute_rayleigh_quotient (const StiffnessMatrixType &stiffness_matrix, const MassMatrixType &mass_matrix, const VectorType &vector)
template<class VectorType , class StiffnessMatrixType , class MassMatrixType , class PreconditionerType , class ConstraintsType >
void one_step_pinvit (typename VectorType::value_type &mu, VectorType &vector, const StiffnessMatrixType &stiffness_matrix, const MassMatrixType &mass_matrix, const PreconditionerType &preconditioner, const ConstraintsType &constraints)
Function Documentation
compute_rayleigh_quotient()
template<class VectorType , class StiffnessMatrixType , class MassMatrixType > VectorType::value_type compute_rayleigh_quotient (const StiffnessMatrixType & stiffness_matrix, const MassMatrixType & mass_matrix, const VectorType & vector)
Definition at line 10 of file pinvit.h.
References Assert, ExcInternalError(), and mass_matrix().
one_step_pinvit()
template<class VectorType , class StiffnessMatrixType , class MassMatrixType , class PreconditionerType , class ConstraintsType > void one_step_pinvit (typename VectorType::value_type & mu, VectorType & vector, const StiffnessMatrixType & stiffness_matrix, const MassMatrixType & mass_matrix, const PreconditionerType & preconditioner, const ConstraintsType & constraints)
Definition at line 32 of file pinvit.h.
References Assert, ExcInternalError(), mass_matrix(), and norm().
Referenced by LaplaceProblem< dim, degree >::solve_system().