SA-PVINT for Elliptic Boundary Value Problems: /github/workspace/include/utilities.h File Reference
utilities.h File Reference
#include <deal.II/base/function.h>
#include <deal.II/base/point.h>
#include <deal.II/base/tensor.h>
#include <deal.II/base/vectorization.h>
#include <deal.II/opencascade/manifold_lib.h>
#include <deal.II/opencascade/utilities.h>
#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/grid_in.h>
Namespaces
ChangeVectorTypes
Functions
template<int dim, typename Number >
VectorizedArray< Number > evaluate_function (const Function< dim > &function, const Point< dim, VectorizedArray< Number >> &p_vectorized, const unsigned int component)
template<int dim, typename Number , int n_components = dim>
Tensor< 1, n_components, VectorizedArray< Number > > evaluate_function (const Function< dim > &function, const Point< dim, VectorizedArray< Number >> &p_vectorized)
template<typename number >
void ChangeVectorTypes::copy (LA::MPI::Vector &out, const dealii::LinearAlgebra::distributed::Vector< number > &in)
template<typename number >
void ChangeVectorTypes::copy (dealii::LinearAlgebra::distributed::Vector< number > &out, const LA::MPI::Vector &in)
template<int dim, typename number >
std::shared_ptr< Table< 2, VectorizedArray< number > > > make_coefficient_table (const Function< dim > &function, const MatrixFree< dim, number, VectorizedArray< number >> &mf_storage)
template<int dim, int spacedim>
void read_grid_and_cad_files (const std::string &grid_file_name, const std::string &ids_and_cad_file_names, Triangulation< dim, spacedim > &tria)
Function Documentation
evaluate_function() [1/2]
template<int dim, typename Number , int n_components = dim> Tensor<1, n_components, VectorizedArray<Number> > evaluate_function (const Function< dim > & function, const Point< dim, VectorizedArray< Number >> & p_vectorized)
Definition at line 59 of file utilities.h.
References AssertDimension, d(), and value.
evaluate_function() [2/2]
template<int dim, typename Number > VectorizedArray<Number> evaluate_function (const Function< dim > & function, const Point< dim, VectorizedArray< Number >> & p_vectorized, const unsigned int component)
Definition at line 42 of file utilities.h.
References d().
Referenced by LaplaceProblem< dim, degree >::assemble_rhs(), and make_coefficient_table().
make_coefficient_table()
template<int dim, typename number > std::shared_ptr<Table<2, VectorizedArray<number> > > make_coefficient_table (const Function< dim > & function, const MatrixFree< dim, number, VectorizedArray< number >> & mf_storage)
Definition at line 125 of file utilities.h.
References evaluate_function(), and n_cells().
Referenced by LaplaceProblem< dim, degree >::setup_multigrid(), and LaplaceProblem< dim, degree >::setup_system().
read_grid_and_cad_files()
template<int dim, int spacedim> void read_grid_and_cad_files (const std::string & grid_file_name, const std::string & ids_and_cad_file_names, Triangulation< dim, spacedim > & tria)
Definition at line 151 of file utilities.h.
References AssertThrow, GridIn< dim, spacedim >::attach_triangulation(), OpenCASCADE::count_elements(), ExcNotImplemented(), GridIn< dim, spacedim >::read(), OpenCASCADE::read_IGES(), OpenCASCADE::read_STEP(), and Triangulation< dim, spacedim >::set_manifold().
Referenced by LaplaceProblem< dim, degree >::make_grid().