var searchData=
[
  ['q1wedgefunction_11230',['Q1WedgeFunction',['http://www.dealii.org/developer/doxygen/deal.II/classFunctions_1_1Q1WedgeFunction.html',1,'Functions']]],
  ['qanisotropic_11231',['QAnisotropic',['http://www.dealii.org/developer/doxygen/deal.II/classQAnisotropic.html',1,'']]],
  ['qcollection_11232',['QCollection',['http://www.dealii.org/developer/doxygen/deal.II/classhp_1_1QCollection.html',1,'hp']]],
  ['qcollection_3c_20dim_20_2d_201_20_3e_11233',['QCollection&lt; dim - 1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classhp_1_1QCollection.html',1,'QCollection&lt; dim - 1 &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/classhp_1_1QCollection.html',1,'hp::QCollection&lt; dim - 1 &gt;']]],
  ['qcollection_3c_20q_5fdim_20_3e_11234',['QCollection&lt; q_dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classhp_1_1QCollection.html',1,'QCollection&lt; q_dim &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/classhp_1_1QCollection.html',1,'hp::QCollection&lt; q_dim &gt;']]],
  ['qduffy_11235',['QDuffy',['http://www.dealii.org/developer/doxygen/deal.II/classQDuffy.html',1,'']]],
  ['qgauss_11236',['QGauss',['http://www.dealii.org/developer/doxygen/deal.II/classQGauss.html',1,'QGauss&lt; dim &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/classSimplex_1_1QGauss.html',1,'Simplex::QGauss&lt; dim &gt;']]],
  ['qgausschebyshev_11237',['QGaussChebyshev',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussChebyshev.html',1,'']]],
  ['qgausslobatto_11238',['QGaussLobatto',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussLobatto.html',1,'']]],
  ['qgausslobatto_3c_201_20_3e_11239',['QGaussLobatto&lt; 1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussLobatto.html',1,'']]],
  ['qgausslobattochebyshev_11240',['QGaussLobattoChebyshev',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussLobattoChebyshev.html',1,'']]],
  ['qgausslog_11241',['QGaussLog',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussLog.html',1,'']]],
  ['qgausslogr_11242',['QGaussLogR',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussLogR.html',1,'']]],
  ['qgaussoneoverr_11243',['QGaussOneOverR',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussOneOverR.html',1,'']]],
  ['qgausspyramid_11244',['QGaussPyramid',['http://www.dealii.org/developer/doxygen/deal.II/classSimplex_1_1QGaussPyramid.html',1,'Simplex']]],
  ['qgaussradauchebyshev_11245',['QGaussRadauChebyshev',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussRadauChebyshev.html',1,'']]],
  ['qgausswedge_11246',['QGaussWedge',['http://www.dealii.org/developer/doxygen/deal.II/classSimplex_1_1QGaussWedge.html',1,'Simplex']]],
  ['qiterated_11247',['QIterated',['http://www.dealii.org/developer/doxygen/deal.II/classQIterated.html',1,'']]],
  ['qmidpoint_11248',['QMidpoint',['http://www.dealii.org/developer/doxygen/deal.II/classQMidpoint.html',1,'']]],
  ['qmilne_11249',['QMilne',['http://www.dealii.org/developer/doxygen/deal.II/classQMilne.html',1,'']]],
  ['qprojector_11250',['QProjector',['http://www.dealii.org/developer/doxygen/deal.II/classQProjector.html',1,'']]],
  ['qr_11251',['QR',['http://www.dealii.org/developer/doxygen/deal.II/classQR.html',1,'']]],
  ['qsimplex_11252',['QSimplex',['http://www.dealii.org/developer/doxygen/deal.II/classQSimplex.html',1,'']]],
  ['qsimplex_3c_202_20_3e_11253',['QSimplex&lt; 2 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classQSimplex.html',1,'']]],
  ['qsimpson_11254',['QSimpson',['http://www.dealii.org/developer/doxygen/deal.II/classQSimpson.html',1,'']]],
  ['qsorted_11255',['QSorted',['http://www.dealii.org/developer/doxygen/deal.II/classQSorted.html',1,'']]],
  ['qsplit_11256',['QSplit',['http://www.dealii.org/developer/doxygen/deal.II/classQSplit.html',1,'']]],
  ['qtelles_11257',['QTelles',['http://www.dealii.org/developer/doxygen/deal.II/classQTelles.html',1,'']]],
  ['qtrapezoid_11258',['QTrapezoid',['http://www.dealii.org/developer/doxygen/deal.II/classQTrapezoid.html',1,'']]],
  ['qtrianglepolar_11259',['QTrianglePolar',['http://www.dealii.org/developer/doxygen/deal.II/classQTrianglePolar.html',1,'']]],
  ['quad_11260',['Quad',['http://www.dealii.org/developer/doxygen/deal.II/structReferenceCell_1_1internal_1_1Info_1_1Quad.html',1,'ReferenceCell::internal::Info']]],
  ['quadrature_11261',['Quadrature',['http://www.dealii.org/developer/doxygen/deal.II/classQuadrature.html',1,'']]],
  ['quadrature_3c_201_20_3e_11262',['Quadrature&lt; 1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classQuadrature.html',1,'']]],
  ['quadrature_3c_20dim_20_2d_201_20_3e_11263',['Quadrature&lt; dim - 1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classQuadrature.html',1,'']]],
  ['quadrature_3c_20structdim_20_3e_11264',['Quadrature&lt; structdim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classQuadrature.html',1,'']]],
  ['quadraturedescriptor_11265',['QuadratureDescriptor',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1MatrixFreeFunctions_1_1MappingInfoStorage_1_1QuadratureDescriptor.html',1,'internal::MatrixFreeFunctions::MappingInfoStorage']]],
  ['quadratureselector_11266',['QuadratureSelector',['http://www.dealii.org/developer/doxygen/deal.II/classQuadratureSelector.html',1,'']]],
  ['qweddle_11267',['QWeddle',['http://www.dealii.org/developer/doxygen/deal.II/classQWeddle.html',1,'']]]
];
