var searchData=
[
  ['data_10327',['Data',['http://www.dealii.org/developer/doxygen/deal.II/structCUDAWrappers_1_1MatrixFree_1_1Data.html',1,'CUDAWrappers::MatrixFree']]],
  ['dataentrybase_10328',['DataEntryBase',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DataOutImplementation_1_1DataEntryBase.html',1,'internal::DataOutImplementation']]],
  ['datahost_10329',['DataHost',['http://www.dealii.org/developer/doxygen/deal.II/structCUDAWrappers_1_1DataHost.html',1,'CUDAWrappers']]],
  ['dataout_10330',['DataOut',['http://www.dealii.org/developer/doxygen/deal.II/classDataOut.html',1,'DataOut&lt; dim, DoFHandlerType &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/classParticles_1_1DataOut.html',1,'Particles::DataOut&lt; dim, spacedim &gt;']]],
  ['dataout_3c_20dim_20_3e_10331',['DataOut&lt; dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOut.html',1,'']]],
  ['dataout_5fdofdata_10332',['DataOut_DoFData',['http://www.dealii.org/developer/doxygen/deal.II/classDataOut__DoFData.html',1,'']]],
  ['dataout_5fdofdata_3c_20dofhandler_3c_20dim_20_3e_2c_20dofhandler_3c_20dim_20_3e_20_3a_3adimension_2c_20dofhandler_3c_20dim_20_3e_20_3a_3aspace_5fdimension_20_3e_10333',['DataOut_DoFData&lt; DoFHandler&lt; dim &gt;, DoFHandler&lt; dim &gt; ::dimension, DoFHandler&lt; dim &gt; ::space_dimension &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOut__DoFData.html',1,'']]],
  ['dataout_5fdofdata_3c_20dofhandlertype_2c_20dofhandlertype_3a_3adimension_20_2d_201_2c_20dofhandlertype_3a_3adimension_20_3e_10334',['DataOut_DoFData&lt; DoFHandlerType, DoFHandlerType::dimension - 1, DoFHandlerType::dimension &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOut__DoFData.html',1,'']]],
  ['dataout_5fdofdata_3c_20dofhandlertype_2c_20dofhandlertype_3a_3adimension_2b1_20_3e_10335',['DataOut_DoFData&lt; DoFHandlerType, DoFHandlerType::dimension+1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOut__DoFData.html',1,'']]],
  ['dataout_5fdofdata_3c_20dofhandlertype_2c_20dofhandlertype_3a_3adimension_2c_20dofhandlertype_3a_3aspace_5fdimension_20_3e_10336',['DataOut_DoFData&lt; DoFHandlerType, DoFHandlerType::dimension, DoFHandlerType::space_dimension &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOut__DoFData.html',1,'']]],
  ['dataoutfaces_10337',['DataOutFaces',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutFaces.html',1,'']]],
  ['dataoutfilter_10338',['DataOutFilter',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutBase_1_1DataOutFilter.html',1,'DataOutBase']]],
  ['dataoutfilterflags_10339',['DataOutFilterFlags',['http://www.dealii.org/developer/doxygen/deal.II/structDataOutBase_1_1DataOutFilterFlags.html',1,'DataOutBase']]],
  ['dataoutinterface_10340',['DataOutInterface',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutInterface.html',1,'']]],
  ['dataoutinterface_3c_200_2c_20spacedim_20_3e_10341',['DataOutInterface&lt; 0, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutInterface.html',1,'']]],
  ['dataoutinterface_3c_202_2c_202_20_3e_10342',['DataOutInterface&lt; 2, 2 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutInterface.html',1,'']]],
  ['dataoutinterface_3c_20dim_2b1_20_3e_10343',['DataOutInterface&lt; dim+1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutInterface.html',1,'']]],
  ['dataoutinterface_3c_20dim_2c_20dim_20_3e_10344',['DataOutInterface&lt; dim, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutInterface.html',1,'']]],
  ['dataoutinterface_3c_20patch_5fdim_2c_20patch_5fdim_20_3e_10345',['DataOutInterface&lt; patch_dim, patch_dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutInterface.html',1,'']]],
  ['dataoutinterface_3c_20patch_5fdim_2c_20patch_5fspace_5fdim_20_3e_10346',['DataOutInterface&lt; patch_dim, patch_space_dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutInterface.html',1,'']]],
  ['dataoutreader_10347',['DataOutReader',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutReader.html',1,'']]],
  ['dataoutrotation_10348',['DataOutRotation',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutRotation.html',1,'']]],
  ['dataoutstack_10349',['DataOutStack',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutStack.html',1,'']]],
  ['dataoutstack_3c_20dim_2c_20spacedim_2c_20void_20_3e_10350',['DataOutStack&lt; dim, spacedim, void &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutStack_3_01dim_00_01spacedim_00_01void_01_4.html',1,'']]],
  ['datapostprocessor_10351',['DataPostprocessor',['http://www.dealii.org/developer/doxygen/deal.II/classDataPostprocessor.html',1,'']]],
  ['datapostprocessor_3c_20spacedim_20_3e_10352',['DataPostprocessor&lt; spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataPostprocessor.html',1,'']]],
  ['datapostprocessorscalar_10353',['DataPostprocessorScalar',['http://www.dealii.org/developer/doxygen/deal.II/classDataPostprocessorScalar.html',1,'']]],
  ['datapostprocessortensor_10354',['DataPostprocessorTensor',['http://www.dealii.org/developer/doxygen/deal.II/classDataPostprocessorTensor.html',1,'']]],
  ['datapostprocessorvector_10355',['DataPostprocessorVector',['http://www.dealii.org/developer/doxygen/deal.II/classDataPostprocessorVector.html',1,'']]],
  ['dataset_10356',['DataSet',['http://www.dealii.org/developer/doxygen/deal.II/classHDF5_1_1DataSet.html',1,'HDF5']]],
  ['datasetdescriptor_10357',['DataSetDescriptor',['http://www.dealii.org/developer/doxygen/deal.II/classQProjector_1_1DataSetDescriptor.html',1,'QProjector']]],
  ['datatransfer_10358',['DataTransfer',['http://www.dealii.org/developer/doxygen/deal.II/classparallel_1_1distributed_1_1Triangulation_1_1DataTransfer.html',1,'parallel::distributed::Triangulation']]],
  ['datavector_10359',['DataVector',['http://www.dealii.org/developer/doxygen/deal.II/structDataOutStack_3_01dim_00_01spacedim_00_01void_01_4_1_1DataVector.html',1,'DataOutStack&lt; dim, spacedim, void &gt;']]],
  ['deal_5fii_5fintermediateflags_10360',['Deal_II_IntermediateFlags',['http://www.dealii.org/developer/doxygen/deal.II/structDataOutBase_1_1Deal__II__IntermediateFlags.html',1,'DataOutBase']]],
  ['defaulthierarchy_10361',['DefaultHierarchy',['http://www.dealii.org/developer/doxygen/deal.II/structhp_1_1FECollection_1_1DefaultHierarchy.html',1,'hp::FECollection']]],
  ['derivativeform_10362',['DerivativeForm',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeForm.html',1,'']]],
  ['derivativeform_3c_201_2c_20dim_2c_20spacedim_20_3e_10363',['DerivativeForm&lt; 1, dim, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeForm.html',1,'']]],
  ['derivativeform_3c_201_2c_20spacedim_2c_20dim_20_3e_10364',['DerivativeForm&lt; 1, spacedim, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeForm.html',1,'']]],
  ['derivativeform_3c_202_2c_20dim_2c_20spacedim_20_3e_10365',['DerivativeForm&lt; 2, dim, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeForm.html',1,'']]],
  ['derivativeform_3c_203_2c_20dim_2c_20spacedim_20_3e_10366',['DerivativeForm&lt; 3, dim, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeForm.html',1,'']]],
  ['derivativeform_3c_204_2c_20dim_2c_20spacedim_20_3e_10367',['DerivativeForm&lt; 4, dim, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeForm.html',1,'']]],
  ['derivativeselector_10368',['DerivativeSelector',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeApproximation_1_1internal_1_1DerivativeSelector.html',1,'DerivativeApproximation::internal']]],
  ['derivativeselector_3c_201_2c_20dim_20_3e_10369',['DerivativeSelector&lt; 1, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeApproximation_1_1internal_1_1DerivativeSelector_3_011_00_01dim_01_4.html',1,'DerivativeApproximation::internal']]],
  ['derivativeselector_3c_202_2c_20dim_20_3e_10370',['DerivativeSelector&lt; 2, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeApproximation_1_1internal_1_1DerivativeSelector_3_012_00_01dim_01_4.html',1,'DerivativeApproximation::internal']]],
  ['derivativeselector_3c_203_2c_20dim_20_3e_10371',['DerivativeSelector&lt; 3, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeApproximation_1_1internal_1_1DerivativeSelector_3_013_00_01dim_01_4.html',1,'DerivativeApproximation::internal']]],
  ['description_10372',['Description',['http://www.dealii.org/developer/doxygen/deal.II/structTriangulationDescription_1_1Description.html',1,'TriangulationDescription']]],
  ['dgp_5fdofs_5fper_5fcomponent_10373',['DGP_dofs_per_component',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1MatrixFreeFunctions_1_1DGP__dofs__per__component.html',1,'internal::MatrixFreeFunctions']]],
  ['dgp_5fdofs_5fper_5fcomponent_3c_201_2c_20degree_20_3e_10374',['DGP_dofs_per_component&lt; 1, degree &gt;',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1MatrixFreeFunctions_1_1DGP__dofs__per__component_3_011_00_01degree_01_4.html',1,'internal::MatrixFreeFunctions']]],
  ['diagonalmatrix_10375',['DiagonalMatrix',['http://www.dealii.org/developer/doxygen/deal.II/classDiagonalMatrix.html',1,'']]],
  ['dictionary_10376',['Dictionary',['http://www.dealii.org/developer/doxygen/deal.II/structUtilities_1_1MPI_1_1internal_1_1ComputeIndexOwner_1_1Dictionary.html',1,'Utilities::MPI::internal::ComputeIndexOwner']]],
  ['dictionaryoptimizer_10377',['DictionaryOptimizer',['http://www.dealii.org/developer/doxygen/deal.II/structDifferentiation_1_1SD_1_1internal_1_1DictionaryOptimizer.html',1,'Differentiation::SD::internal']]],
  ['dictionarypayload_10378',['DictionaryPayLoad',['http://www.dealii.org/developer/doxygen/deal.II/classUtilities_1_1MPI_1_1internal_1_1ComputeIndexOwner_1_1DictionaryPayLoad.html',1,'Utilities::MPI::internal::ComputeIndexOwner']]],
  ['dictionarysubstitutionvisitor_10379',['DictionarySubstitutionVisitor',['http://www.dealii.org/developer/doxygen/deal.II/classDifferentiation_1_1SD_1_1internal_1_1DictionarySubstitutionVisitor.html',1,'Differentiation::SD::internal']]],
  ['dimension_3c_3a_3apoint_3c_20dim_2c_20number_20_3e_20_3e_10380',['dimension&lt;::Point&lt; dim, Number &gt; &gt;',['http://www.dealii.org/developer/doxygen/deal.II/structboost_1_1geometry_1_1traits_1_1dimension_3_1_1Point_3_01dim_00_01Number_01_4_01_4.html',1,'boost::geometry::traits']]],
  ['directionalprojectionmanifold_10381',['DirectionalProjectionManifold',['http://www.dealii.org/developer/doxygen/deal.II/classOpenCASCADE_1_1DirectionalProjectionManifold.html',1,'OpenCASCADE']]],
  ['directoryname_10382',['DirectoryName',['http://www.dealii.org/developer/doxygen/deal.II/classPatterns_1_1DirectoryName.html',1,'Patterns']]],
  ['discretetime_10383',['DiscreteTime',['http://www.dealii.org/developer/doxygen/deal.II/classDiscreteTime.html',1,'']]],
  ['distortedcelllist_10384',['DistortedCellList',['http://www.dealii.org/developer/doxygen/deal.II/structTriangulation_1_1DistortedCellList.html',1,'Triangulation']]],
  ['distributedtriangulationbase_10385',['DistributedTriangulationBase',['http://www.dealii.org/developer/doxygen/deal.II/classparallel_1_1DistributedTriangulationBase.html',1,'parallel']]],
  ['distributedtriangulationbase_3c_201_2c_20spacedim_20_3e_10386',['DistributedTriangulationBase&lt; 1, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classparallel_1_1DistributedTriangulationBase.html',1,'']]],
  ['distributedtriangulationbase_3c_20dim_2c_20dim_20_3e_10387',['DistributedTriangulationBase&lt; dim, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classparallel_1_1DistributedTriangulationBase.html',1,'']]],
  ['dofaccessor_10388',['DoFAccessor',['http://www.dealii.org/developer/doxygen/deal.II/classDoFAccessor.html',1,'']]],
  ['dofaccessor_3c_200_2c_201_2c_20spacedim_2c_20level_5fdof_5faccess_20_3e_10389',['DoFAccessor&lt; 0, 1, spacedim, level_dof_access &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFAccessor_3_010_00_011_00_01spacedim_00_01level__dof__access_01_4.html',1,'']]],
  ['dofaccessor_3c_20dimension_5f_2c_20dimension_5f_2c_20space_5fdimension_5f_2c_20level_5fdof_5faccess_20_3e_10390',['DoFAccessor&lt; dimension_, dimension_, space_dimension_, level_dof_access &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFAccessor.html',1,'']]],
  ['dofcellaccessor_10391',['DoFCellAccessor',['http://www.dealii.org/developer/doxygen/deal.II/classDoFCellAccessor.html',1,'']]],
  ['doffaces_10392',['DoFFaces',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFFaces.html',1,'internal::DoFHandlerImplementation']]],
  ['doffaces_3c_201_20_3e_10393',['DoFFaces&lt; 1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFFaces_3_011_01_4.html',1,'internal::DoFHandlerImplementation']]],
  ['doffaces_3c_202_20_3e_10394',['DoFFaces&lt; 2 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFFaces_3_012_01_4.html',1,'internal::DoFHandlerImplementation']]],
  ['doffaces_3c_203_20_3e_10395',['DoFFaces&lt; 3 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFFaces_3_013_01_4.html',1,'internal::DoFHandlerImplementation']]],
  ['dofhandler_10396',['DoFHandler',['http://www.dealii.org/developer/doxygen/deal.II/classDoFHandler.html',1,'DoFHandler&lt; dim, spacedim &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/classhp_1_1DoFHandler.html',1,'hp::DoFHandler&lt; dim, spacedim &gt;']]],
  ['dofhandler_3c_201_2c_20spacedim_20_3e_10397',['DoFHandler&lt; 1, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFHandler.html',1,'']]],
  ['dofhandler_3c_20dim_20_3e_10398',['DoFHandler&lt; dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFHandler.html',1,'']]],
  ['dofinfo_10399',['DoFInfo',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1MatrixFreeFunctions_1_1DoFInfo.html',1,'internal::MatrixFreeFunctions::DoFInfo'],['http://www.dealii.org/developer/doxygen/deal.II/classMeshWorker_1_1DoFInfo.html',1,'MeshWorker::DoFInfo&lt; dim, spacedim, number &gt;']]],
  ['dofinfobox_10400',['DoFInfoBox',['http://www.dealii.org/developer/doxygen/deal.II/classMeshWorker_1_1DoFInfoBox.html',1,'MeshWorker']]],
  ['dofinvalidaccessor_10401',['DoFInvalidAccessor',['http://www.dealii.org/developer/doxygen/deal.II/classDoFInvalidAccessor.html',1,'']]],
  ['doflevel_10402',['DoFLevel',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFLevel.html',1,'internal::DoFHandlerImplementation']]],
  ['dofobjects_10403',['DoFObjects',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFObjects.html',1,'internal::DoFHandlerImplementation']]],
  ['dofobjects_3c_201_20_3e_10404',['DoFObjects&lt; 1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFObjects.html',1,'internal::DoFHandlerImplementation::DoFObjects&lt; 1 &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFObjects.html',1,'DoFObjects&lt; 1 &gt;']]],
  ['dofobjects_3c_202_20_3e_10405',['DoFObjects&lt; 2 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFObjects.html',1,'internal::DoFHandlerImplementation::DoFObjects&lt; 2 &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFObjects.html',1,'DoFObjects&lt; 2 &gt;']]],
  ['dofoutputoperator_10406',['DoFOutputOperator',['http://www.dealii.org/developer/doxygen/deal.II/classAlgorithms_1_1DoFOutputOperator.html',1,'Algorithms']]],
  ['dofpair_10407',['DoFPair',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1MGTransfer_1_1DoFPair.html',1,'internal::MGTransfer']]],
  ['dofprintsolverstep_10408',['DoFPrintSolverStep',['http://www.dealii.org/developer/doxygen/deal.II/classDoFPrintSolverStep.html',1,'']]],
  ['dot_10409',['Dot',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1VectorOperations_1_1Dot.html',1,'internal::VectorOperations']]],
  ['dotproduct_10410',['DotProduct',['http://www.dealii.org/developer/doxygen/deal.II/structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1DotProduct.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['double_10411',['Double',['http://www.dealii.org/developer/doxygen/deal.II/classPatterns_1_1Double.html',1,'Patterns']]],
  ['double_5fcontraction_5fresult_10412',['double_contraction_result',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1SymmetricTensorAccessors_1_1double__contraction__result.html',1,'internal::SymmetricTensorAccessors']]],
  ['double_5fcontraction_5fresult_3c_202_2c_202_2c_20dim_2c_20number_2c_20othernumber_20_3e_10413',['double_contraction_result&lt; 2, 2, dim, Number, OtherNumber &gt;',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1SymmetricTensorAccessors_1_1double__contraction__result_3_012_00_012_00_01dim_bde24087db8a52ec06f500b41dd95304.html',1,'internal::SymmetricTensorAccessors']]],
  ['duplicatedcommunicator_10414',['DuplicatedCommunicator',['http://www.dealii.org/developer/doxygen/deal.II/classUtilities_1_1MPI_1_1DuplicatedCommunicator.html',1,'Utilities::MPI']]],
  ['dx_10415',['DX',['http://www.dealii.org/developer/doxygen/deal.II/structGridOutFlags_1_1DX.html',1,'GridOutFlags']]],
  ['dxflags_10416',['DXFlags',['http://www.dealii.org/developer/doxygen/deal.II/structDataOutBase_1_1DXFlags.html',1,'DataOutBase']]],
  ['dynamicsparsitypattern_10417',['DynamicSparsityPattern',['http://www.dealii.org/developer/doxygen/deal.II/classDynamicSparsityPattern.html',1,'']]]
];
